### ISSUE TITLE
Only absolute URLs are supported

### ISSUE THREAD

**Issue by JUnderd0wn** [Brutalbeard/send-sms#7]
Hi @Brutalbeard, it's probably user error as I'm new to all this.
I'm trying to test this and when executing node .  The response is originalMessage: 'Only absolute URLs are supported'

My platform address is for the sandpit, so https://platform.devtest.ringcentral.com.

Any advice/ pointers would be appreciated.
Thanks
James

**Comment by Brutalbeard** [comment]
@JUnderd0wn this is in your `.env` file correct? Could always try putting it directly in the `index.js` file instead, just make sure if you put credentials there, that you don't accidentally push it to Github :-P

**Comment by JUnderd0wn** [comment]
Yeah, user error :) sorted now thanks. 
Now it's stalling at Subscription created. I think my dev account can't send SMS. I assume this is the same for sending messages from one account to another, rather than "sending an SMS"?

**Comment by Brutalbeard** [comment]
Yup same for sure
